{
    "name": "Health Insurance Claim (HIC)",
    "version": "18.0.1.0.0",
    "category": "Healthcare",
    "summary": "Health Insurance Claim Management System",
    "author": "Mate JSC",
    "support": "info@mate.com.vn",
    "website": "https://mate.com.vn",
    "depends": [
        "base",
        "his",
    ],
    "data": [
        "security/ir.model.access.csv",
        "data/sequence.xml",
        "data/benefit_code_data.xml",
        "data/professional_title_data.xml",
        "data/medical_service_code_data.xml",
        "views/reference_level_view.xml",
        "views/benefit_code_views.xml",
        "views/bhyt_object_code_views.xml",
        "views/kcb_object_code_views.xml",
        "views/discharge_type_code_views.xml",
        "views/accident_code_views.xml",
        "views/department_views.xml",
        "views/hospital_bed_views.xml",
        "views/medical_facility_views.xml",
        "views/category_views.xml",
        "views/payment_rate_views.xml",
        "views/employee_views.xml",
        "menu/menu.xml",
        "demo/sync_his_demo.xml",
    ],
    "installable": True,
    "auto_install": False,
    "application": True,
    "sequence": 1,
    "license": "LGPL-3",
}
